name: etf-index-tracker
on:
  push:
    paths:
      - 'etf-index-tracker/**'  # 只监控 etf-index-tracker 目录变化
      - '!html/**'  # 排除 html 目录变化（防止循环触发）
  pull_request:
    paths:
      - 'etf-index-tracker/**'
  schedule:
    - cron: '0 10 * * *'  # UTC时间10:00（对应北京时间18:00）
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level (e.g., info, debug)'
        required: false
        default: 'info'

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须的写入权限
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # 更可靠的缓存路径
          key: pip-${{ hashFiles('etf-index-tracker/requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./etf-index-tracker  # 安装依赖时进入子目录

      - name: Execute main.py
        run: python main.py
        working-directory: ./etf-index-tracker  # 生成文件到 etf-index-tracker/html

      # 新增调试步骤
      - name: Verify files
        run: |
          echo "查看生成的文件："
          ls -l ./etf-index-tracker/html/

      - name: Commit and Push
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 进入子目录操作
          cd ./etf-index-tracker

          # 配置 Git
          git config --global --add safe.directory '*'  # 修复权限问题
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 提交变更
          git add html/* data/*
          git status
          git commit -m "Auto-update charts $(date '+%Y-%m-%d') [skip ci]" || echo "No changes"
          git push origin HEAD:master
